# Generated by Django 3.0.6 on 2020-06-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gal', '0003_auto_20200611_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='displayHeight',
            new_name='display_height',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='displayWidth',
            new_name='display_width',
        ),
    ]
